services:
    elastica.data_collector:
        class: GBProd\ElasticaBundle\DataCollector\ElasticaDataCollector
        tags:
            - { name: 'data_collector', template: 'ElasticaBundle:Collector:elastica', id: 'elastica' }
        arguments:
            - '@elastica.logger'
        public: true
